### ISSUE TITLE
About testing for sRGB-sRGB image denoising

### ISSUE THREAD

**Issue by YangGangZhiQi** [demonsjin/Blind2Unblind#12]
Hi, thanks for this great works. After reading this paper,  I can see that the algorithm have been tested for Synthetic dataset denoising,  raw-RGB dataset denoising and FM denoising, but not for sRGB-sRGB dataset denoising. What is the reason that your group not do experiment for sRGB-sRGB dataset denoising?  I am curious about whether it could be used for sRGB-sRGB denoising. Hope for your reply. Thanks.

**Comment by zejinwang** [comment]
Hi, thanks for your interest and appreciation of our work. Regarding your question about sRGB-sRGB dataset denoising, we mainly considered the following aspects:

In our research, we chose to perform denoising in the raw domain because this maximizes the assumption of spatial independence of Poisson-Gaussian noise. When images go through the ISP pipeline, structured noise may be introduced, making the statistical properties of the noise more complex. Therefore, we conducted experiments on Synthetic dataset denoising, raw-RGB dataset denoising, and FM denoising but did not perform experiments on sRGB-sRGB dataset denoising.

However, this does not mean that our method cannot be applied to sRGB-sRGB dataset denoising. In fact, you can try to apply our method to sRGB data, but some adjustments to the algorithm may be needed to adapt to the noise characteristics in the sRGB data. In practice, you may need to adjust the noise modeling and modify the denoising strength according to the noise distribution in the sRGB data.

I hope this answer is helpful to you. If you have any other questions, please feel free to ask. Thank you again for your interest in our work!
